[project]
name = "fastapi-server"
version = "0.1.0"
description = "FastAPI app for running summarization model."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.124.2",
    "nltk>=3.9.2",
    "transformers>=4.57.3",
    "uvicorn>=0.38.0",
]
